version: 2

cache_key: &cache_key
  key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle.kts" }}-{{ checksum "library/build.gradle.kts" }}-{{ checksum "plugin/build.gradle.kts" }}

jobs:
  check:
    working_directory: ~/pluto
    docker:
      - image: circleci/android:api-28-alpha
    parallelism: 4
    environment:
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          <<: *cache_key

      - run:
          name: Check
          command: ./gradlew check test
      - store_artifacts:
          path: app/build/reports
      - store_artifacts:
          path: library/build/reports
      - store_artifacts:
          path: plugin/build/reports

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

  build:
    working_directory: ~/pluto
    docker:
      - image: circleci/android:api-28-alpha
    parallelism: 4
    environment:
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          <<: *cache_key

      - run:
          name: Build
          command: ./gradlew build

workflows:
  version: 2
  check_build:
    jobs:
      - check:
          filters:
            branches:
              only:
                - master
                - /release/.*/
                - /feature/.*/
      - build:
          requires:
            - check
          filters:
            branches:
              only:
                - master
                - /release/.*/
